[package]
name = "bookman"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.34", features = ["bundled", "bundled-sqlcipher"] }
arboard = { version = "3", features = ["wayland-data-control"] }
clap = "4"
skim = "0.16"
scraper = "0.23.1"
